# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: git config user.email "v.corwic@gmail.com"
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages 
        folder: build 

  lint:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Code Base
      uses: github/super-linter/slim@v4.8.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILTER_REGEX_EXCLUDE: .*test.*
        JAVASCRIPT_ES_CONFIG_FILE: ./.eslintrc.json
        #VALIDATE_JAVASCRIPT_STANDARD: false
        #VALIDATE_TYPESCRIPT_STANDARD: false
        #JAVASCRIPT_DEFAULT_STYLE: prettier
        #TYPESCRIPT_DEFAULT_STYLE: prettier


    
